# Generated by Django 5.2.17 on 2026-09-18 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, help_text='Used in the menu address. Filled in from the name if left empty.', unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Hidden categories and their dishes disappear from the menu.', verbose_name='shown on the menu')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True, help_text='One or two sentences.')),
                ('logo', models.FileField(blank=True, help_text='SVG or transparent PNG, light artwork (it sits on the dark photo).', upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('hero_image', models.ImageField(blank=True, help_text='Landscape, at least 1920 × 1080.', upload_to='brand/')),
                ('currency', models.CharField(default='LBP', help_text='ISO 4217 code, e.g. LBP, USD, EUR.', max_length=3)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Lowercase, e.g. signature, vegan, vegetarian, gluten_free, spicy, new.', unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=60)),
                ('hours', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='menu.restaurant')),
            ],
            options={
                'verbose_name_plural': 'opening hours',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='menu.restaurant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Filled in from the name if left empty.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Square photo, at least 600 × 600.', upload_to='dishes/')),
                ('is_available', models.BooleanField(default=True, help_text='Unavailable dishes stay on the menu, greyed out.', verbose_name='available today')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished dishes are hidden from the menu.', verbose_name='shown on the menu')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='dishes', to='menu.tag')),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
