# Generated by Django 5.2.17 on 2026-09-24 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_enabled',
            field=models.BooleanField(default=True, help_text='Off removes the delivery choice from the cart.', verbose_name='home delivery offered'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Added to the order when the customer chooses delivery. 0 is shown as “Free”.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_note',
            field=models.CharField(blank=True, help_text='Shown under the delivery choice, e.g. “Delivery inside Chhim only”.', max_length=160),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pickup_enabled',
            field=models.BooleanField(default=True, help_text='Off removes the pickup choice from the cart.', verbose_name='pickup offered'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only, in full international form: 9613000000. Leave empty to turn ordering off.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', 'Digits only, in full international form: 9613000000 (no +, spaces or leading zero).')], verbose_name='WhatsApp number for orders'),
        ),
    ]
