# Generated by Django 5.2.17 on 2026-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservation_enabled',
            field=models.BooleanField(default=True, help_text='Off removes the table reservation choice from the cart.', verbose_name='table reservation offered'),
        ),
    ]
