# Generated by Django 5.2.17 on 2026-09-27 07:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Filled in from the name if left empty.', unique=True)),
                ('description', models.CharField(blank=True, help_text='One short line.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Optional. A photo of the whole spread.', upload_to='offers/')),
                ('price', models.DecimalField(decimal_places=2, help_text='What the customer pays for everything in the offer.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Hidden offers disappear from the Offers window.', verbose_name='shown on the menu')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='menu.dish')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.offer')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
